const API = {
  HOME: 'home',
  // FLASH_SALE: 'flash_sale',
  BLOG_HOME: "blog/home",
  PRODUCT_DETAILS: 'product_details',
  FILTER: 'filter',
  SMART_SHOPPING: 'engagement/category',
  ADD_TO_CART: 'add_to_cart',
  CREATE_CART: 'create_cart',
  GET_CART: 'get_cart',
  REMOVE_CART_ITEM: 'remove_cart_item',
  CART_PRODUCT_IDS: 'cart_product_ids',
  PRODUCTS: 'products',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub_category',
  Wishlist: 'wishlist',
  SETTING: 'setting',
  REGISTER: 'register',
  LOGIN: 'login',
  LOGOUT: 'logout',
  REMOVE_WISHLIST: 'remove_wishlist',
  ADD_WISHLIST: 'add_wishlist',
  ADD_SHIPPING_ADDRESS: 'add_shipping_address',
  COUNTRY: 'country',
  CITY: 'city',
  AREA: 'area',
  SHIPPING_ADDRESS: 'shipping_address',
  DELETE_SHIPPING_ADDRESS: 'delete_shipping_address',
  CHECKOUT: 'checkout',
  PLACE_ORDER: 'place_order',
  ORDERS: 'orders',
  ORDER_DETAILS: 'order_details',
  UPDATE_SHIPPING_ADDRESS: 'update_shipping_address',
  PROFILE: 'profile',
  UPDATE_PROFILE_PHOTO: 'update-profile-photo',
  UPDATE_PROFILE: 'update-profile',
  CHANGE_PASSWORD: 'change_password',
  ALLLANGUAGES: 'allLanguages',
  SOCIAL_LOGIN: 'social_login',
  TRANSLATIONS: 'translations',
  VALIDATEBARCODE: 'validateBarcode',
  ACCOUNT_DELETE: 'account_delete',
  GET_COUNTRY: 'country',
  Merge_Cart: 'merge_cart',
  GETRECOMMENDEDPRODUCTS: 'getRecommendedProducts',
  FORGOTPASSWORD: 'forgot'
};

export default API;
